version: '3.1'

services:
  db:
    image: postgres:15.1
    environment:
      POSTGRES_DB: assignmentspringsecurity
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
